### ISSUE TITLE
Add troubleshooting for SQL Server version problem

### ISSUE THREAD

**Issue by smalers** [OpenCDSS/cdss-website-hydrobase#4]
I had trouble attaching a SQL Server snapshot because my SQL Server was too old.  The following is the warning:

![image (16)](https://user-images.githubusercontent.com/6448274/161467022-13d18157-d839-491c-8c14-92c06e8c6eda.png)

My suggestion is to add this to troubleshooting and perhaps have some discussion of SQL Server versions.  Maybe the snapshots need release notes and more information about what version of SQL Server they were written for.  If the State's position on this is that users must update SQL Server, then just say that.

Note that at some point old databases will not work with current SQL Server.  I don't know if that is an issue or not for modeling.

**Comment by macphersonbr** [comment]
I will add troubleshooting documentation here: https://opencdss.state.co.us/hydrobase/index.html#troubleshooting

and here: https://opencdss.state.co.us/tstool/14.0.4/doc-user/troubleshooting/troubleshooting/

**Comment by macphersonbr** [comment]
Updated here: https://opencdss.state.co.us/tstool/14.2.2/doc-user/troubleshooting/troubleshooting/#issue-14-sql-server-express-out-of-date

and here: https://opencdss.state.co.us/hydrobase/index.html#sql-server-express-out-of-date

Will wait to make TSTool 14.2.2 documentation "latest" until discussion with Steve.
